// <auto-generated />
namespace HiriKata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class newcat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newcat));
        
        string IMigrationMetadata.Id
        {
            get { return "201503172304129_new-cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
